// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD9z9EHXMBFEwapX0BsXc9nxd2cSru-LzU',
    appId: '1:469573359751:web:02e5c730b168d5393e4022',
    messagingSenderId: '469573359751',
    projectId: 'notesapp-d4732',
    authDomain: 'notesapp-d4732.firebaseapp.com',
    storageBucket: 'notesapp-d4732.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCkOvJTuULUUjbOn4jnDE9gTTfXg6_pgYY',
    appId: '1:469573359751:android:e2ae61f9f164c7923e4022',
    messagingSenderId: '469573359751',
    projectId: 'notesapp-d4732',
    storageBucket: 'notesapp-d4732.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC6UO2TwLmB4PV2RmtGD6LWx2Yqieehrgc',
    appId: '1:469573359751:ios:778362993545482e3e4022',
    messagingSenderId: '469573359751',
    projectId: 'notesapp-d4732',
    storageBucket: 'notesapp-d4732.firebasestorage.app',
    iosClientId: '469573359751-8cb943njtbdqo9r1ji5kpedlf5h4dej8.apps.googleusercontent.com',
    iosBundleId: 'com.example.mynoteapps',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC6UO2TwLmB4PV2RmtGD6LWx2Yqieehrgc',
    appId: '1:469573359751:ios:778362993545482e3e4022',
    messagingSenderId: '469573359751',
    projectId: 'notesapp-d4732',
    storageBucket: 'notesapp-d4732.firebasestorage.app',
    iosClientId: '469573359751-8cb943njtbdqo9r1ji5kpedlf5h4dej8.apps.googleusercontent.com',
    iosBundleId: 'com.example.mynoteapps',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD9z9EHXMBFEwapX0BsXc9nxd2cSru-LzU',
    appId: '1:469573359751:web:4d744a8c483f8ed23e4022',
    messagingSenderId: '469573359751',
    projectId: 'notesapp-d4732',
    authDomain: 'notesapp-d4732.firebaseapp.com',
    storageBucket: 'notesapp-d4732.firebasestorage.app',
  );
}
